name: WCP Studios
favicon: null
layout_spectrum: 0.99606
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#484848'
    - '#585858'
    - '#717171'
    - '#828282'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0
purpose: []
