name: WCP Studios
favicon: null
layout_spectrum: 0.07952894968912005
typography_spectrum: 0.5048351839650422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0809'
    - '#342c29'
    - '#b8b2a6'
    - '#655b52'
    - '#d3cfc3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
